# version: '2'

services:
    docker-homelab:
        stdin_open: true
        tty: true
        ports:
            - 10000:10000/tcp
            - 67:67/tcp
            - 67:67/udp
        image: docker-homelab:latest